### ISSUE TITLE
Option to minimize window...

### ISSUE THREAD

**Issue by Lirieth** [fechan/JackJack#28]
...to "JackJack"-headline would be much appreciated ;-)

**Comment by fechan** [comment]
Had a crack at this already by hiding the locations list and shrinking the size of the JackJack window and I couldn't get it to work. The window would jump around on hide/show, and trying to set it programmatically didn't work (and it would override the player-set window position across sessions).

Possibly I could have the titlebar be a separate frame which is draggable and anchor the window content to the titlebar, both of which would have the WoW map set as the parent, then show/hide the content frame on title bar click. Possible issue is that the window content will no longer be draggable itself; might be inconsistent with the rest of WoW UI behavior. Probably also want to source a wider titlebar texture and a show/hide icon in the WoW files in this case.

No guarantees this will work or whether this will be added in the future.

**Comment by fechan** [comment]
Splitting the window into two frames works, so the title and searchbar are on its own frame separate from the contents frame, containing all the location buttons and stuff. You can't drag the entire JJ window with the contents frame though, but you can with the title frame, but this is minor.

When there's no search, the contents frame is hidden, which I think is pretty intuitive.

![image](https://user-images.githubusercontent.com/56131910/160993681-58bd7265-2843-4449-a4a8-029bb5222ca1.png)

![image](https://user-images.githubusercontent.com/56131910/160994538-452761f6-c077-4ff1-b5de-72609376e93e.png)

It still says "Showing first of 3000 possibilities" though, even when it's blank. Easy fix.

**Comment by fechan** [comment]
Feature is ready for inclusion in upcoming 1.7 release

**Comment by Lirieth** [comment]
Thank you very much 👍 It's very kind of you to consider this option and spend your time implementing it :-)
This will make the use of this addon much more comfortable for a lot of people 🙂

**Comment by Lirieth** [comment]
Gee, I can thump up my own comment 🙄

**Comment by fechan** [comment]
Feature branch is merged with master. JJ 1.7 is still in development, but if you're really desperate for this feature you can download the source code and put it in your addons folder manually.

**Comment by fechan** [comment]
I'm releasing this as 1.6.1 instead of 1.7 as planned, since I seem to have lost most of my motivation to work on the 1.7 features. It's uploaded as a github release and will be updated on curse/wowinterface soon.
