### ISSUE TITLE
[question/suggestion] Disabling the auto-opening with map?

### ISSUE THREAD

**Issue by tflo** [fechan/JackJack#36]
Interesting addon! But the no-go thingy is that the frame automatically opens every time I call the map.

In >90% of the cases when I open the map I certainly do not want the help of JackJack, that is, the frame – even in its minimized form – is just screen clutter most of the time.

So, is there an option to disable the auto-opening, and to just use a keybind or (preferably) a slash command to open JackJack only when I want/need it? If not, then please take this as suggestion.

– Tom

**Comment by fechan** [comment]
You can't hide the JackJack window entirely, but I can add an option for this.

I might add an X button to the corner that would have it close, and you could reopen it with one of those little minimap buttons or using a command `/jj <locationname>`.

**Comment by tflo** [comment]
Sounds like a good solution. (Assuming that closing the frame prevents it from future auto-popping, i.e. the state should be written to the account-wide SV table.)

**Comment by fechan** [comment]
Reopening since this isn't implemented yet

**Comment by fechan** [comment]
Latest version of JackJack (2.3) now implements this.
